# Generated by Django 2.0.13 on 2019-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='uploader',
        ),
    ]
