# Generated by Django 2.0.13 on 2019-04-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_files_uploader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='file_path',
            new_name='file_name',
        ),
    ]
