# Generated by Django 2.0.13 on 2019-04-19 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_files_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='nodes',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
